### ISSUE TITLE
Is HA broken on master?

### ISSUE THREAD

**Issue by srbry** [cloudfoundry-incubator/eirini-release#152]
### Description

Configured multiple instances of NATs with HA turned on, the second instance fails to start.

### Steps to reproduce

configure valus.yaml

```yaml
config:
  HA: true
sizing:
  nats:
    count: 2
```

### What was expected to happen

2 NATs instances would start and all would be good.

### What actually happened

Second nats instance failed to start, logs are quite helpful.

```
++++ curl --silent --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H 'Authorization: bearer <token>' https://172.20.0.1:443/apis/apps/v1/statefulsets/nats/namespaces/scf/
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'spec'
+++ replicas=
+++ '[' nats '!=' '' -a '' '!=' '' ']'
+++ '[' nats == '' ']'
+++ '[' '' == '' ']'
+++ echo 'Cannot get replicas from kubernetes API, retrying'
Cannot get replicas from kubernetes API, retrying
+++ sleep 1
+++ (( i ++ ))
+++ (( i < 5  ))
+++ '[' nats == '' ']'
+++ '[' '' == '' ']'
+++ echo 'Cannot get replicas from kubernetes API, exit'
Cannot get replicas from kubernetes API, exit
+++ exit 1
++ KUBE_NATS_CLUSTER_IPS=
```

### Additional information (optional)

Having looked into this on a working container (the first nats instance). 
It looks like the error is down too: /opt/fissile/startup/scripts/configure-HA-hosts.sh:51

```
replicas=$(k8s_api apis/apps/v1"/statefulsets/${statefulset_name}" | json_get [\'spec\'][\'replicas\'])
```

This should be
```
replicas=$(k8s_api apis/apps/v1 "/statefulsets/${statefulset_name}" | json_get [\'spec\'][\'replicas\'])
```

*Note* the space between v1 and statefulsets, the issue here is the building of the URL. Leading too `apis/apps/v1/statefulsets/nats/namespaces/scf/` where it should  be `apis/apps/v1/namespaces/scf/statefulsets/nats/`

This is on commit ref `a5f2a697c04ad6b401e3dc114a26a25352ea4ff1`

I am struggling to find where this code is coming from to provide a fix as it does not match https://github.com/SUSE/scf/blob/master/container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh

**Comment by julz** [comment]
Hi @srbry - good news/bad news on this. Good news: we believe this is fixed in a newer version of scf, Bad news: unfortunately we're still using an older version, and may continue on an older version for a little while.

The context for the bad news is we're trying to avoid spending much effort keeping up with scf these days because we're planning - now that teams are spinning up to do this! - to start delegating the problem of deploying CF-with-eirini to other teams asap (e.g. via the new [CF Operator](https://github.com/cloudfoundry-incubator/cf-operator) from the Quarks team and the new [cf-for-k8s effort](https://github.com/cloudfoundry/cf-for-k8s)). 

Hopefully(?) for the moment you can work around this by staying with 1 instance of NATs and relying on being able to start a new instance quickly for HA. The bug should then be fixed either when we upgrade scf or - hopefully/likely sooner - when we move over to CF Operator/CF-for-k8s.

**Comment by srbry** [comment]
Hi @julz thanks for your response, I moved over to using kubecf and haven't had any issues, I can also confirm that just overriding the sizings for the NATs instance back to 1 did seem to work.
