### ISSUE TITLE
Doesn't work with nginx:alpine based containers

### ISSUE THREAD

**Issue by XanderStrike** [cloudfoundry-incubator/eirini-release#156]
### Description

Doesn't seem to work with my website.

It's a straightforward `nginx:alpine` container with some config and static files copied over.

[Dockerfile here](https://github.com/XanderStrike/web/blob/master/astandke/Dockerfile)

### Steps to reproduce

`cf push astandke -o xanderstrike/web:astandke` 

### What was expected to happen

Site is available at `astandke.CF_DOMAIN` and looks [right](https://astandke.com/)

### What actually happened

App never reachable. `cf apps` says started with 0/1 instances. Kubectl get pods eventually says CrashLoopBackOff.

Logs include: 
```
2020-02-19T10:35:28.66-0800 [unknown/769922a8-5346-11ea-8d1d-42010a8a016a] OUT 2020/02/19 18:35:28 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
2020-02-19T10:35:28.66-0800 [unknown/769922a8-5346-11ea-8d1d-42010a8a016a] OUT nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

### Suggested fix (optional)

Allow processes in the container to run as root maybehaps

### Additional information (optional)

Related to cloudfoundry/cf-for-k8s#31

**Comment by georgethebeatle** [comment]
Thanks for reporting this @XanderStrike, it is fixed in master and will be in next release. If you still have similar problems after you get the fix, please make sure that your cluster does not have a catch-all restricted pod security policy.

**Comment by gdankov** [comment]
Hey @XanderStrike! We slightly changed the way Eirini handles docker images that run with the root user. Now Eirini does not allow such images to run, by default (because of security reasons), but we added a way to override this behavior. For more information, please take a look [here](https://github.com/cloudfoundry-incubator/eirini-release/tree/a17923afc87dfc49ec314b3626f25fcdfcfbacbb#docker-images-runnig-with-the-root-user). 

If you have any issues with the new behavior, please let us know.
