### ISSUE TITLE
Eirini Events High memory consumption

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry-incubator/eirini-release#175]
### Description

  We did a scalability tests on cf-for-k8s version [v-0.6.0](https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.6.0).  We deployed 1000 apps out of which 50 apps are meant to crash frequently. We could see `eirini-events` pod was consuming high memory > 10Gi and automatically restart happens and memory reduces.  We suspect some memory leak. 
![image](https://user-images.githubusercontent.com/29627753/92374408-4ad46300-f11d-11ea-8439-1f140ab5f084.png)

### Steps to reproduce

Deploy crashing apps - [Example](https://github.com/cloudfoundry/diego-stress-tests/blob/master/cedar/assets/stress-app/main.go#L55-L62)  and observe the eirini-events pod memory usage.

### What actually happened

  Memory consumption is  very high

**Comment by kieron-pivotal** [comment]
Hi @KesavanKing ,

We're having a problem reproducing this. We're not seeing any significant memory increases with 400 happy apps, and 50 crashing apps. If you could give us some steps to reproduce the environment you're seeing this in that would be good.

Also though, we have totally rewritten the event reporter code since the version included in cf-for-k8s v0.6.0. It might be worth repeating the experiment with the next cf-for-k8s, as it could well be already fixed.

**Comment by KesavanKing** [comment]
Hi 👋 ,

We did our scalability tests for the pre-release 0.7.0 of cf-for-k8s and the issue didn't occur. Memory usage was under the control.
![image](https://user-images.githubusercontent.com/29627753/94891533-f57f3d80-049f-11eb-8dce-ee0365d3628b.png)
 

Thanks for the support.
