### ISSUE TITLE
Extract `eirini-controller` from `eirini` and `eirini-release`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry-incubator/eirini-release#217]
As our controller grows and evolves, trying to make the old REST codebase coexist with the new CRDs one is getting more and more convoluted. Let's extract all the CRD-related code to a new repository called `eirini-controller`. The new repository should include all CRD-releated code, tests, deploy manifests, scripts.

As we do this, let's understand which code is shared by the two implementations, wether it's worth duplicating it, importing in the new project as a library, or rewriting it, maybe leveraging the controller runtime client instead of the clientset?

**Comment by danail-branekov** [comment]
After some experiments and discussions we decided that we would not use the kubebuilder development flow/tools as they do not really fit our use cases. Instead we are just going to pick up things we like, e.g. generating CRD yamls.

I have copied the https://github.com/cloudfoundry-incubator/eirini repo to https://github.com/cloudfoundry-incubator/eirini-controller (in order to preserve the valuable history), deleted non-eirini-controller bits (might be more leftovers though) and removed the references to `eirini` (so that `eirini-controller` has no dependencies to `eirini`)
