### ISSUE TITLE
cf logs doesn't work on GKE

### ISSUE THREAD

**Issue by axel7born** [cloudfoundry-incubator/eirini-release#65]
Hi, 
cf logs doesn't work on GKE due to missing mounted volumes.

We had a conversation on slack about the issue:
https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1556095403095400

Mounting the volumes solves the problem and allows us to get the logs.

Thanks,
Axel

**Comment by KaiHofstetter** [comment]
We saw the same issue with Gardener running Kubernetes on AWS, which also used a docker container-runtime ('docker://18.6.1'). The same mount path was missing there as well.

**Comment by hev** [comment]
You might want to consider reading logs directly out of the filesystem rather than use fluentd->loggregator->logcache components. This would making cf logs work more natively and similar to something like [kail](https://github.com/boz/kail).

**Comment by voelzmo** [comment]
@hev Thanks for the pointers. Is my understanding correct that you'd recommend not using the loggregator stack when deploying CF on K8s? Could you help me understand more about the reasoning behind this? I guess using `kail` we could just match the logs by label and be done with it.

One of the experiences I'd like to maintain is adding a service to stream your application logs to. `cf create-service` and `cf bind-service`, call a URL and start analyzing your logs – that feels nice.

**Comment by hev** [comment]
Yeah, the main reason we moved away from the Loggregator stack is the difference in the Docker logging driver. Since the docker logging driver redirect `std.err` and `std.out` to the filesystem it enforces a back pressure contract on workloads that log alot. Reading out of the filesystem and then using loggregator to transport results in lost messages occasionally for no performance gain. We also never completed work to the containerized loggregator components to scale past a single instance. 

That said you can get most of the functionality of the cli out of kubectl natively, and syslog draining / firehose like functionality are available as `sink-resources` over in [knative/observability](https://github.com/knative/observability)

**Comment by alex-slynko** [comment]
Hi
We have GKE in our environment and the logging is working.

**Comment by alex-slynko** [comment]
Additionally, we have a story to optionally disable some Eirini components, such as log producer https://www.pivotaltracker.com/story/show/170313550
